alias ls="ls -lahG"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias mkdir="mkdir -pv"
alias clr="clear && tmux clear-history"
alias j="jump"
alias tls="tmux ls"
alias ta="tmux attach-session -t"
