- name: clone the vim source (because we're compiling from scratch)
  register: clone_vim
  hg: >
    repo=https://vim.googlecode.com/hg/
    dest={{ home }}/src/vim
    revision=v7-4-307

- name: clean the vim folder if anything's changed
  when: clone_vim|changed
  shell: cd {{ home }}/src/vim && make distclean

- name: register perl_lib
  register: perl_lib
  shell: bash -lc "plenv prefix"
  changed_when: false

- name: configure and compile the vim source
  register: build_vim
  shell: >
    bash -lc "cd {{ home }}/src/vim && make distclean && ./configure {{ vim_options }}"
    creates={{ home }}/src/vim/src/auto/config.h

- name: install the just-compiled vim bins
  when: build_vim|changed
  sudo: yes
  shell: bash -lc "cd {{ home }}/src/vim && make install"
