- name: clone the vim source (because we're compiling from scratch)
  register: clone_vim
  hg: >
    repo=https://vim.googlecode.com/hg/
    dest={{ home }}/src/vim
    revision=v7-4-307

- name: clean the vim folder if anything's changed
  when: clone_vim|changed
  shell: cd {{ home }}/src/vim && make distclean

- name: register perl_lib
  register: perl_lib
  shell: bash -lc "plenv prefix"
  changed_when: false

- name: register ruby_lib
  register: ruby_bin
  shell: bash -lc "rbenv which ruby"
  changed_when: false

- name: configure and compile the vim source
  sudo: yes
  register: build_vim
  shell: >
    PERL_LIB={{ perl_lib.stdout }}/lib
    bash -lc "cd {{ home }}/src/vim && make distclean && ./configure --with-ruby-command={{ ruby_bin.stdout }} {{ vim_options }}"

- name: install the just-compiled vim bins
  when: build_vim|changed
  sudo: yes
  shell: bash -lc "cd {{ home }}/src/vim && make install"
