- name: install extra deps
  homebrew: name={{ item }} state=present
  with_items:
    - luajit

- name: Install fully featured vim in Darwin
  register: installed_vim
  homebrew: >
    name=macvim
    state=present
    install_options=override-system-vi,with-lua,with-luajit,with-python3

