- name: Install extra dependencies
  sudo: yes
  apt : pkg={{ item }} state=installed
  with_items:
    - git
    - mercurial
    - exuberant-ctags
    - perl
    - libperl-dev
    - python3-dev
    - python3
    - python-dev
    - python
    - libextutils-xspp-perl
    - tcl-dev

