- name: Install extra dependencies
  sudo: yes
  apt : pkg={{ item }} state=installed
  with_items:
    - git
    - mercurial
    - exuberant-ctags
    - perl
    - libperl-dev
    - python3-dev
    - python3
    - python-dev
    - python
    - libextutils-xspp-perl
    - tcl-dev

- name: make sure we have ~/src/ as a real dir
  file: path=~/src state=directory

- name: clone the source for luajit
  git: >
    repo=http://luajit.org/git/luajit-2.0.git
    dest=~/src/luajit
    version=v2.0.3

- name: compile luajit
  shell: cd ~/src/luajit && bash -lc "make"

- name: install luajit
  sudo: yes
  shell: cd ~{{ ansible_user_id }}/src/luajit && make install

- name: clone the vim source (because we're compiling from scratch)
  hg: >
    repo=https://vim.googlecode.com/hg/
    dest=~/src/vim
    revision=v7-4-307

- name: import vim installation variables
  include_vars: "main.yml"

- name: configure and compile the vim source
  shell: cd ~/src/vim; bash -lc "./configure {{ vim_options }}"

- name: install the just-compiled vim bins
  sudo: yes
  shell: cd ~{{ ansible_user_id }}/src/vim && make install
