# install vim dotfiles
- include: "Darwin_extras.yml"
  when: os_family == "Darwin"

- include: "RedHat_extras.yml"
  when: os_family == "RedHat"

- include: "Debian_extras.yml"
  when: os_family == "Debian"

- include: compile.yml

- name: install vimrc
  copy: src=dotfiles/{{ item.src }} dest={{ home }}/{{ item.dest }}
  with_items:
    - { src: 'vimrc', dest: '.vimrc' }

- name: Grab Vundle from Github
  git: >
    repo=git://github.com/gmarik/Vundle.vim.git
    dest={{ home }}/Vundle.vim

- name: Run Vundle's PluginInstall to grab the latest
  shell: cd; bash -lc "vim +PluginInstall +qall" creates={{ home }}/.vim/bundle
