# install vim dotfiles
- name: install vimrc
  template: src=dotfiles/{{ item.src }} dest=~{{ ansible_user_id }}/{{ item.dest }}
  with_items:
    - { src: 'vimrc', dest: '.vimrc' }

- name: install vimrc.d
  synchronize: src=dotfiles/{{ item.src }} dest=~/{{ item.dest }}
  with_items:
    - { src: 'vimrc.d/', dest: '.vimrc.d' }

- name: Install fully featured vim in Debian
  when: ansible_os_family == "Debian"
  apt : pkg=vim-gtk state=installed
  sudo: yes

- name: Install fully featured vim in Darwin
  when: ansible_os_family == "Darwin"
  register: installed_vim
  homebrew: >
    name=macvim
    state=present
    install_options=override-system-vi,with-lua,with-luajit,with-python3

- name: Grab Vundle from Github
  git: >
    repo=git://github.com/gmarik/Vundle.vim.git
    dest=~{{ ansible_user_id }}/.vim/bundle/Vundle.vim

- name: Run Vundle's PluginInstall to grab the latest
  shell: cd; bash -lc "vim +PluginInstall +qall"
  when: installed_vim|changed
