# install vim dotfiles
- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

- include: compile.yml

- name: install vimrc
  file: state=link src=dotfiles/{{ item.src }} dest={{ home }}/{{ item.dest }}
  with_items:
    - { src: 'vimrc', dest: '.vimrc' }
    - { src: 'vim/tabular_extras.vim',
        dest: '.vim/bundle/tabular/after/plugin/tabular_extras.vim' }

- name: Grab Vundle from Github
  git: >
    repo=git://github.com/gmarik/Vundle.vim.git
    dest={{ home }}/Vundle.vim

- name: Run Vundle's PluginInstall to grab the latest
  shell: cd; bash -lc "vim +PluginInstall +qall" creates={{ home }}/.vim/bundle
