# install vim dotfiles
- include: "Darwin_extras.yml"
  when: ansible_os_family == "Darwin"

- include: "RedHat_extras.yml"
  when: ansible_os_family == "RedHat"

- include: "Debian_extras.yml"
  when: ansible_os_family == "Debian"

- name: install vimrc
  template: src=dotfiles/{{ item.src }} dest=~{{ ansible_user_id }}/{{ item.dest }}
  with_items:
    - { src: 'vimrc', dest: '.vimrc' }

- name: install vimrc.d
  synchronize: src=dotfiles/{{ item.src }} dest=~/{{ item.dest }}
  with_items:
    - { src: 'vimrc.d/', dest: '.vimrc.d' }

- name: Grab Vundle from Github
  git: >
    repo=git://github.com/gmarik/Vundle.vim.git
    dest=~{{ ansible_user_id }}/.vim/bundle/Vundle.vim

- name: Run Vundle's PluginInstall to grab the latest
  shell: cd; bash -lc "vim +PluginInstall +qall"
  when: installed_vim|changed
