#TODO add a when here
- name: grab the lua source
  get_url: >
    url=http://www.lua.org/ftp/lua-5.2.3.tar.gz
    dest=/tmp/lua_source.tar.gz

- name: get a checksum from the source
  changed_when: false
  register: lua_retrieved_checksum
  shell: md5sum /tmp/lua_source.tar.gz

- name: fail if the checksums don't match
  when: '"dc7f94ec6ff15c985d2d6ad0f1b35654" not in lua_retrieved_checksum.stdout'
  fail: "Checksums don't match"

- name: make sure src/lua exists
  file: path=~/src/lua state=directory

- name: unarchive the file
  unarchive: >
    creates=~/src/lua/lua-5.2.3/Makefile
    dest=~/src/lua/
    src=/tmp/lua_source.tar.gz

- name: configure and make
  when: os_family == "Darwin"
  register: build_lua
  shell: cd ~/src/lua/lua-5.2.3 && make macosx

- name: configure and make
  when: os_family != "Darwin"
  shell: cd ~/src/lua/lua-5.2.3 && make linux

- name: install
  sudo: yes
  shell: cd ~{{ ansible_user_id }}/src/lua/lua-5.2.3 && make install
