- include: "Darwin_reqs.yml"
  when: os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

# install normal lua
- include: lua.yml

# install luajit
- include: luajit.yml

# not working
#- include: luarocks.yml

# not working
#- include: luakit.yml
