---
- name: install bash_profile
  template: >
    src=dotfiles/bash_profile
    dest={{ home }}/.bash_profile

- name: make sure .bash.d dir exists on target
  file: path={{ home }}/.bash.d state=directory

- name: install .bash.d dir
  synchronize: >
    src="dotfiles/bash.d/"
    dest={{ home }}/.bash.d

- name: copy the source completion script
  copy: >
    src=99_plugin_completion.bash
    dest={{ home }}/.bash.d/99_plugin_completion.bash

- name: make sure .marks dir exists on target
  file: path={{ home }}/.marks state=directory

- include: "Darwin_reqs.yml"
  when: os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

- include: tmux.yml
