# gather information first I guess
- hosts: all
  tasks:
    - group_by: key={{ ansible_distribution }}
      changed_when: false

- hosts: all
  vars_files:
    - vars/main.yml
  roles:
    - role: common

    - role: shell
      tags: ["dotfiles", "shell"]

    - role: dotfiles
      tags: ["dotfiles"]

    - role: editor
      tags: ["dotfiles", "editor"]

    - role: languages
      tags: ["go", "ruby", "rbenv"]

    - role: replication
      tags: ["config"]

    - role: virtualization
      tags: ["virtualization"]

    - role: packaging
      tags: ["packaging"]
