# gather information first I guess
- hosts: "{{ lookup('env', 'ANSIBLE_TARGETS') }}"
  tasks:
    - group_by: key={{ ansible_distribution }}
      changed_when: false

- hosts: "{{ lookup('env', 'ANSIBLE_TARGETS') }}"
  vars_files:
    - vars/main.yml
    - "vars/{{ ansible_os_family | replace('\"', '') | replace(' ', '') }}.yml"
  roles:
    - role: common

    - role: perl
      tags: ["perl"]

    - role: fonts
      tags: ["fonts"]

    - role: shell
      tags: ["dotfiles", "shell"]

    - role: dotfiles
      tags: ["dotfiles"]

    - role: editor
      tags: ["editor"]

    - role: languages
      tags: ["go", "ruby", "rbenv", "scala", "clojure", "php", "lua"]

    - role: virtualization
      tags: ["virtualization"]

    - role: packaging
      tags: ["packaging"]

    - role: desktop
      tags: ["desktop"]

    - role: replication
      tags: ["config"]

