# gather information first I guess
- hosts: all
  tasks:
    - group_by: key={{ ansible_distribution }}
      changed_when: false

- hosts: all
  roles:
    - role: common
    - role: dotfiles
      tags: ["dotfiles"]
    - role: rbenv
      tags: ["ruby", "rbenv"]
    - role: ruby-multi
      tags: ["ruby", "ruby-build", "ruby-install"]
      versions: # first is default
        - 2.1.0
        - 2.0.0-p353
        - 1.9.3-p484
        - 1.8.7-p375

    - role: go
      tags: ["go"]
