- name: Create scala lib dir
  file: path={{ scala_lib_path }} state=directory

- name: Create directory for Scala {{ scala_version_name }}
  file: path={{ scala_lib_path_target }} state=directory
  register: create_scala_dir

- name: Download scala v{{ scala_version}}
  when: create_scala_dir|changed
  get_url: >
    url={{ scala_download_url}}
    dest=/tmp/{{ scala_archive_file }}
    force=no

- name: Unpack Scala into the target path
  when: create_scala_dir|changed
  unarchive: >
    src=/tmp/{{ scala_archive_file }}
    dest={{ scala_lib_path }}
    copy=false

- name: link the binaries
  file: >
    src={{ scala_lib_path_target }}/bin/{{ item }}
    dest={{ scala_link_target }}/{{ item }}
    state=link
    force=yes
  with_items:
    - scala
    - scalac
    - fsc
    - sbaz
    - sbaz-setup
    - scaladoc
    - scalap

- name: Create directory for Scala {{ scala_version_name }}
  file: path={{ sbt_lib_path_target }} state=directory
  register: create_sbt_dir

- name: download sbt v{{ sbt_version }}
  when: create_sbt_dir|changed
  register: download_sbt
  get_url: >
    url={{ sbt_download_url }}
    dest={{ sbt_lib_path_target }}
    force=no

- name: install the sbt shell script
  when: download_sbt|changed
  template: >
    src=sbt.j2
    dest={{ home }}/managed-bin/sbt
    mode=755
    owner={{ ansible_user_id }}
    force=yes

- name: run sbt once
  when: download_sbt|changed
  shell: cd && bash -lc "sbt exit"
