---
- include: "Darwin_reqs.yml"
  when: os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

- name: make sure the {{ home }}/code/config dir exists
  file: path={{ home }}/code/config state=directory

- name: copy the current set of playbooks to the new machine
  synchronize:  >
    src={{ inventory_dir }}/../
    dest={{ config_dir }}
    recursive=yes

