- name: Make sure we have a {{ home }}/src folder
  file: path={{ home }}/src state=directory

- name: Grab the source via mercurial
  hg: >
    repo=https://code.google.com/p/go
    dest={{ home }}/go
    revision={{ go_version_target }}

- name: Build the source
  shell: cd {{ home }}/all.bash"

