- name: Make sure we have a ~/src folder
  file: path=~{{ ansible_user_id }}/src state=directory

- name: Grab the source via mercurial
  hg: >
    repo=https://code.google.com/p/go
    dest=~{{ ansible_user_id }}/src/go
    revision={{ go_version_target }}

- name: Build the source
  shell: cd ~{{ ansible_user_id }}/src/go/src; bash -lc "./all.bash"

