- name: install the prereqs for compiling the Go source on Debian
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - gcc
    - libc6-dev
    - libc6-dev-i386
    - mercurial
    - bzr
    - git

