- name: git clone interesting things
  register: go_git_clone_task
  git: >
    repo=git://{{ item.repo }}
    dest={{ gopath }}/src/{{ item.repo }}
    version={{ item.version }}
  with_items:
    go_binaries

- name: install any binaries that were changed
  when: go_git_clone_task | changed
  shell: >
    cd {{ gopath }}/src/{{ item.repo }};
    bash -lc "go get ./... && go install"
  with_items:
    go_binaries
