---
- name: Add the Go bin script (sets up GOPATH, etc.) to .bash.d
  copy: src=99_go.bash dest=~{{ ansible_user_id }}/.bash.d/

- name: Include the OS-specific vars file
  include_vars: "{{ ansible_os_family }}.yml"

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Ensure there is a tarballs dir in ~
  file: path=~{{ ansible_user_id }}/tarballs state=directory

- name: Download the Go tarball
  when: go_version|failed or go_version.stdout != go_version_target
  get_url: url={{ go_download_location }}
           dest=~{{ ansible_user_id }}/tarballs/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}

- name: Extract the Go tarball if Go is not yet installed or if it is not the desired version
  when: go_version|failed or go_version.stdout != go_version_target
  sudo: yes
  command: tar -C /usr/local -xf ~{{ ansible_user_id }}/tarballs/{{ go_tarball }}
