---
- name: install virtualbox and vagrant via brew-cask
  when: ansible_os_family == "Darwin"
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - virtualbox
    - vagrant

- name: install virtualbox and vagrant via apt
  when: ansible_os_family == "Debian"
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - virtualbox
    - vagrant

- name: git clone gox (a packer dependency)
  git: >
    repo=git://github.com/mitchellh/gox
    dest={{ gopath }}/src/github.com/mitchellh/gox
    version=v0.3.0

- name: install gox (a packer dependency)
  shell: bash -lc "cd {{ gopath }}/src/github.com/mitchellh/gox && go get ./... && go install"

- name: clone packer
  git: >
      repo=git://github.com/mitchellh/packer
      dest={{ gopath }}/src/github.com/mitchellh/packer
      version=5cd2cfa5638fd90a01de1fe94f0a2b9eb16f8ba2

- name: install packer via make
  shell: bash -lc "cd {{ gopath }}/src/github.com/mitchellh/packer && make"
