---
- name: make sure we have some important directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ home }}/managed-bin"
    - "{{ home }}/src"
    - "{{ home }}/code"
    - "{{ home }}/tmp"

- include: "Darwin_reqs.yml"
  when: os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

- name: find various ssh keys
  shell: ssh-keyscan {{ item }}
  register: source_control_host_keys
  changed_when: false
  with_items:
    - github.com
    - bitbucket.org
    - code.google.com

- name: SSH | Add Git repo host key to known_hosts file
  lineinfile: >
    create=yes
    dest={{ home }}/known_hosts
    state=present
    line='{{ item.stdout }}'
  with_items: source_control_host_keys.results
