---
- include: "Darwin_reqs.yml"
  when: os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

- name: Remove .bashrc (we use .bash_profile)
  file: path=~{{ ansible_user_id }}/.bashrc state=absent

