---
- name: make sure we have some important directories
  file: path={{ item }} state=directory
  with_items:
    - "~/managed-bin"
    - "~/src"
    - "~/code"

- include: "Darwin_reqs.yml"
  when: os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

