- name: create the composer directory if it doesn't exist
  file: >
    path=~{{ ansible_user_id }}/.composer/vendor
    state=directory

- name: link ~/.composer/vendor/bin to managed-bin
  file: >
    src=~{{ ansible_user_id }}/managed-bin
    dest=~{{ ansible_user_id }}/.composer/vendor/bin
    state=link

- name: grab composer
  shell: >
    cd && phpbrew install-composer
    creates=/home/ciarand/.phpbrew/.phpbrew/bin/composer
