- name: create the composer directory if it doesn't exist
  file: >
    path={{ home }}/.composer/vendor
    state=directory

- name: link {{ home }}/.composer/vendor/bin to managed-bin
  file: >
    src={{ home }}/managed-bin
    dest={{ home }}/.composer/vendor/bin
    state=link

- name: symlink the composer.json and composer.lock files
  # until we can figure out better pathing support, this is a hack
  file: >
    src={{ config_dir }}/dotfiles/php/composer.{{ item }}
    dest={{ home }}/.composer/composer.{{ item }}
    state=link
  with_items:
    - lock
    - json

- name: grab composer
  shell: >
    bash -lc "phpbrew switch {{ item.version }} && phpbrew install-composer"
    creates={{ home }}/.phpbrew/.phpbrew/bin/composer
  with_items:
    - "{{ php_versions | last }}"

- name: run composer global install
  register: composer_global_install
  shell: cd && composer global install creates=/home
  changed_when: '"Nothing to install or update" not in composer_global_install.stdout'
