- name: install php5 deps (ansible apt module doesn't support build-dep)
  sudo: yes
  shell: apt-get build-dep -y php5
  register: php5_build_dep
  changed_when: >
    "0 upgraded, 0 newly installed" not in php5_build_dep.stdout

- name: install php53, dev-deps from apt
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - php5
    - php5-dev
    - php-pear
    - libxslt1-dev
    - re2c
    - libxml2
    - libxml2-dev
    - php5-cli
    - libfreetype6
    - libfreetype6-dev
    - libpng12-0
    - libpng12-dev
    - libjpeg-dev
    - libjpeg8-dev
    - libjpeg8
    - libgd2-xpm-dev
    - libxpm4
    - libgettextpo-dev
    - libicu48
    - libicu-dev
    - libmhash-dev
    - libmhash2
    - libmcrypt-dev
    - libmcrypt4
    - libmysqlclient-dev
    - libmysqld-dev
    - libmysqlclient18
    - libc-client2007e
    - libc-client2007e-dev
    - libfcgi-dev
    - libfcgi0ldbl
    - libjpeg62-dbg
    - firebird2.1-dev
    - firebird2.5-dev
