- include: "Darwin_reqs.yml"
  when: os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

- name: grab phpbrew from the internet
  get_url: >
    url=https://raw.github.com/c9s/phpbrew/master/phpbrew
    dest=~/managed-bin/phpbrew
    mode=755
  register: get_phpbrew

- name: init phpbrew
  when: get_phpbrew|changed
  shell: bash -lc "phpbrew init"

- name: copy the source phpbrew thing
  copy: >
    src=99_phpbrew.bash
    dest=~/.bash.d/99_phpbrew.bash

- name: check which phps we have installed
  register: installed_phps
  shell: bash -lc "phpbrew list"
  changed_when: false

- name: install missing phps
  when: item.version not in installed_phps.stdout 
  shell: bash -lc "phpbrew install {{ item.version }} {{ item.flags }}"
  with_items: php_versions

- include: phpdbg.yml

- include: composer.yml
