- name: check current version of phpdbg
  register: phpdbg_version
  changed_when: false
  shell: cd && phpdbg --version

- name: decide whether the version of phpdbg is correct
  set_fact: >
    has_correct_phpdbg_version=(
      phpdbg_version.rc != 0
      or
      phpdbg_target_version not in phpdbg_version.stdout
    )

- name: clone phpdbg for all phps
  when: not has_correct_phpdbg_version and (item | version_compare("5.4.0", ">="))
  git: >
    repo=https://github.com/krakjoe/phpdbg
    dest={{ php_build_dir}}/php-{{ item }}/sapi/phpdbg
    version=v{{ phpdbg_target_version }}
  with_items: php_versions

- name: reconfigure the php source and build phpdbg
  when: not has_correct_phpdbg_version and (item | version_compare("5.4.0", ">="))
  shell: >
    cd {{ php_build_dir }}/php-{{ item }} && make distclean 2>/dev/null;
    ./buildconf --force
    && ./config.nice --enable-phpdbg
    && make -j8
    && make install-phpdbg
    creates={{ php_bin_dir }}/php-{{ item }}/bin/phpdbg
  with_items: php_versions
