---
# ruby specific dependencies

- name: Install build reqs for Ruby
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - exuberant-ctags
    - git-core
    - libreadline6
    - libreadline6-dev
    - libreadline-dev
    - libsqlite3-0
    - libsqlite3-dev
    - libssl-dev
    - libyaml-dev
    - libc6-dev
    - libncurses5-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - openssl
    - sqlite3
    - subversion
    - zlib1g
    - zlib1g-dev

- name: Installs rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=~{{ ansible_user_id }}/.rbenv

- name: Ensure fragments bash dir exists
  file: dest=~{{ ansible_user_id }}/.bash.d/ state=directory

- name: Installs rbenv bash file
  copy: src=50_rbenv.bash dest=~{{ ansible_user_id }}/.bash.d/50_rbenv.bash mode=700 owner={{ ansible_user_id }}

- name: Source rbenv bash file in dot bashrc
  lineinfile: dest=~{{ ansible_user_id }}/.bash_profile regexp="rbenv" insertafter=EOF line="source ~/.bash.d/50_rbenv.bash" create=yes

- name: Creates plugin directory
  file: path=~{{ ansible_user_id }}/.rbenv/plugins/ owner={{ ansible_user_id }} group={{ ansible_user_id }} mode=0755 state=directory

- name: Installs ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest=~{{ ansible_user_id }}/.rbenv/plugins/ruby-build

