---
# ruby compilation requirements (OS specific)
- include: "Darwin_reqs.yml"
  when: os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: os_family == "Debian"

- name: Installs rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest={{ home }}/.rbenv

- name: Ensure {{ home }}/bash.d exists
  file: dest={{ home }}/ state=directory

- name: Installs rbenv bash file
  copy: >
    src=99_rbenv.bash
    dest={{ home }}/99_rbenv.bash
    mode=700 owner={{ ansible_user_id }}
    force=yes

- include: plugins.yml
