---
# ruby compilation requirements (OS specific)
- include: "Darwin_reqs.yml"
  when: ansible_os_family == "Darwin"

- include: "RedHat_reqs.yml"
  when: ansible_os_family == "RedHat"

- include: "Debian_reqs.yml"
  when: ansible_os_family == "Debian"

- name: Installs rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=~{{ ansible_user_id }}/.rbenv

- name: Ensure ~/bash.d exists
  file: dest=~{{ ansible_user_id }}/.bash.d/ state=directory

- name: Installs rbenv bash file
  copy: >
    src=99_rbenv.bash
    dest=~{{ ansible_user_id }}/.bash.d/99_rbenv.bash
    mode=700 owner={{ ansible_user_id }}
    force=yes

- include: plugins.yml
