- name: clone the powerline repo
  notify: install powerline fonts
  git: >
    repo=https://github.com/Lokaltog/powerline.git
    dest=~/src/powerline

- name: clone the powerline-fonts repo
  notify: install powerline fonts
  git: >
    repo=git@github.com:Lokaltog/powerline-fonts.git
    dest=~/src/powerline-fonts
